name: Publish artifacts
description: Publishes artifacts after CI process
inputs:
  target:
    description: target triples for built artifact
  profile:
    description: "'debug' or 'release'"
  os:
    description: "'darwin', 'windows', or 'linux'"
  arch:
    description: "'x86_64' or 'aarch64'"
runs:
  using: node20
  main: dist/index.js
